spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://kc.services.theosmo.com/auth/realms/VRM-DEV
server:
  port: 8081

logging:
  level:
    org.springframework.*: DEBUG
